artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  remote_url: https://github.com/gititsid/Datasets/raw/main/us_visa.csv
  raw_data_path: artifacts/data_ingestion/data.csv
  database: visa_verdict
  raw_collection: raw_data

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  processed_data: artifacts/data_preprocessing/us_visa_processed.csv
  database: visa_verdict
  raw_collection: raw_data
  processed_collection: processed_data

data_validation:
  root_dir: artifacts/data_validation
  database: visa_verdict
  raw_collection: raw_data
  processed_collection: processed_data

data_transformation:
  root_dir: artifacts/data_transformation
  database: visa_verdict
  processed_collection: processed_data
  random_state: 42
  data_transformer: artifacts/data_transformation/data_transformer.pkl

model_training:
  root_dir: artifacts/model_training
  test_size: 0.2
  random_state: 42
  hyperparameters:
    - n_estimators: 200
    - max_depth: 20
  experiment_name: RandomForestClassifier
  model_path: artifacts/model_training/model.pkl

model_evaluation:
    root_dir: artifacts/model_evaluation
    data_transformer: artifacts/data_transformation/data_transformer.pkl
    model_path: artifacts/model_training/model.pkl
    train_metrics: artifacts/model_evaluation/train_metrics.json
    test_metrics: artifacts/model_evaluation/test_metrics.json

prediction:
    root_dir: artifacts/prediction
    data_transformer: artifacts/data_transformation/data_transformer.pkl
    model_path: artifacts/model_training/model.pkl
